### ISSUE TITLE
Create and edit account

### ISSUE THREAD

**Issue by JoakimHaglund** [s1ggelin/fogelformedlingen#15]
**Description:**
Create a singup page and a page for editing the account
**Backend:**
- [ ] Define Account data model.
- [ ] Create singup page. (this might need breaking down into smaller issues)
- [ ] Create page for editing Account.
- [ ] Add navigation to signup 
- [ ] Add navigation to Account editing page
**Frontend:**
