### ISSUE TITLE
Handle ads

### ISSUE THREAD

**Issue by s1ggelin** [s1ggelin/fogelformedlingen#24]
**Description:**
Create a page for handling ads.

**Backend** 

- [ ] Define Ad data model
- [ ] Create ad CRUD functionality

**Frontend**

- [ ]  Create page for creating ads
- [ ]  Create page for editing ads
- [ ] Create page for deleting ads
