### ISSUE TITLE
Create web-api

### ISSUE THREAD

**Issue by jsirugo** [s1ggelin/fogelformedlingen#30]
-Issues under this has to do with API-

- [ ] Create web-API
- [ ] Fetch API information to code(json?)
- [ ] Create documentation (Postman/Swagger?)
- [ ] Implement security (?) for API
